role_assignment:
  driver: oidc
  oidc_role_mapper:
    role_claim: groups
    role_mapping:
      - role_name: admin
        claim_value: homelab-admins
      - role_name: user
        claim_value: parents
      - role_name: user
        claim_value: kids
      - role_name: guest
        claim_value: guest
